repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # Pre-commit hooks sürümü
    hooks:
      - id: end-of-file-fixer  # Son satırdaki boşlukları düzeltir
      - id: trailing-whitespace  # Gereksiz boşlukları temizler
